### ISSUE TITLE
LaneFilterNode' object has no attribute 'getDistributionImage

### ISSUE THREAD

**Issue by mweiss17** [duckietown/sim-duckiebot-lanefollowing-demo#8]
When I run docker-compose -f docker-compose-lf.yml up

I get this error about a million times:
lanefollow_1 [0m [ERROR] [1541453542.657670]: bad callback: <bound method LaneFilterNode.processSegments of <main.LaneFilterNode object at 0xed12f2b0>>
�lanefollow_1 �[0m Traceback (most recent call last):
�lanefollow_1 �[0m File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
lanefollow_1 |�[0m cb(msg)
lanefollow_1 |�[0m File "/home/software/catkin_ws/src/10-lane-control/lane_filter/src/lane_filter_node.py", line 137, in processSegments
lanefollow_1 |�[0m belief_img = self.getDistributionImage(self.filter.belief, segment_list_msg.header.stamp)
lanefollow_1 |�[0m AttributeError: 'LaneFilterNode' object has no attribute 'getDistributionImage'
lanefollow_1 |�[0m

It sort of looks like lane_follow is receiving something:
�[36mlanefollow_1 |�[0m [INFO] [1541453523.488410]: [LineDetectorNode] 401:In the last 10.2 s: received 102 (10.0 fps) processed 100 (9.8 fps) skipped 2 (0.2 fps) (2%) �[36mlanefollow_1 |�[0m [INFO] [1541453533.420216]: [LineDetectorNode] 501:# segments: white 1 yellow 22 red 0

and kinda works... Will keep looking at this in a couple hours.

�[36mlanefollow_1             |�[0m Latencies:
�[36mlanefollow_1             |�[0m                acquired | total latency     4.7 ms | delta wall     None clock     None
�[36mlanefollow_1             |�[0m                 decoded | total latency    21.5 ms | delta wall  16.8 ms clock  16.9 ms
�[36mlanefollow_1             |�[0m                 resized | total latency    22.1 ms | delta wall   0.7 ms clock   0.6 ms
�[36mlanefollow_1             |�[0m                detected | total latency    36.6 ms | delta wall  14.4 ms clock  15.5 ms
�[36mlanefollow_1             |�[0m                prepared | total latency    41.8 ms | delta wall   5.2 ms clock   4.7 ms
�[36mlanefollow_1             |�[0m           --pub_lines-- | total latency    43.3 ms | delta wall   1.5 ms clock   1.6 ms
�[36mlanefollow_1             |�[0m                   drawn | total latency    45.8 ms | delta wall   2.5 ms clock   2.3 ms
�[36mlanefollow_1             |�[0m               pub_image | total latency    46.3 ms | delta wall   0.5 ms clock   0.4 ms
�[36mlanefollow_1             |�[0m    pub_edge/pub_segment | total latency    57.1 ms | delta wall  10.8 ms clock  10.4 ms
�[36mlanefollow_1             |�[0m

**Comment by bhairavmehta95** [comment]
@liampaull do we know what this is?

**Comment by liampaull** [comment]
Let me look into it

**Comment by mweiss17** [comment]
Output of docker stats on my box. Apparently the lanefollow container is throwing down 25 gigs of data and using, if I understand [this](https://docs.docker.com/engine/reference/commandline/stats/#examples) correctly, a lot of cpu time...

![screen shot 2018-11-06 at 8 19 35 am](https://user-images.githubusercontent.com/2440148/48066931-e51f9480-e19c-11e8-9b74-db3eb4457459.png)

**Comment by mweiss17** [comment]
At the top of `docker-compose-lf.yml` you can downgrade the version from 3 to 2.2, then add these:

```
cpu_count: 2
cpu_percent: 50
cpus: 0.5

```
to the lanefollow block, like this:

  ```
  lanefollow:
        build:
            context: .
            dockerfile: DockerfileLFSlim
        networks:
        - gym-duckietown-net
        command: /bin/bash -c "source /home/software/docker/env.sh && ./set_vehicle_name.sh && roslaunch /home/software/lf_slim.launch"
        environment:
        - "HOSTNAME=default"
        cpu_count: 2
        cpu_percent: 50
        cpus: 0.5

```

and now my computer doesn't catch on fire while I try to debug
![screen shot 2018-11-06 at 8 36 59 am](https://user-images.githubusercontent.com/2440148/48067805-287b0280-e19f-11e8-9484-c6f80891e62e.png)
